language: cpp
sudo: required
dist: xenial
before_install:
    - sudo apt-get update
    - sudo apt-get install -y libboost-all-dev
    - sudo apt-get install -y liblog4cxx10-dev
    - sudo apt-get install -y rapidjson-dev
    - sh autogen.sh
script:
    - ./configure && make
